install.packages("fpp") 
install.packages("forecast") 
install.packages("fma")
library(fma) 
library(fpp)
library(forecast)
set.seed(16225)
y <- arima.sim(list(order = c(1,1,0), ar = 0.7), n = 300)
plot(y, xlab = "Time", ylab = "Data", main = "Time Series Plot")
acf(y, lag.max = 250, main = "ACF Plot for the time series")
pacf(y, lag.max = 250, main = "PACF Plot for the time series")
adf.test(y)
diff_y <- diff(y, lag = 1, differences = 1)
plot(diff_y, lw = 2, ylab = "d1") 
adf.test(diff_y, alternative = "stationary")
arima_y=auto.arima(y, trace= T, stationary = FALSE, seasonal = TRUE, ic = c("aic"))
summary(y)
checkresiduals(arima_y,lag = 20)
Box.test (arima_y$residuals, lag = 1, type = "Ljung")
fcast=forecast(arima_y, h = 6)
autoplot
plot(fcast)

